<?php
/**
 * Created by PhpStorm.
 * User: wxiao
 * Date: 2017/7/13
 * Time: 上午10:49
 */

//// 1、创建类
class className {

    /// 1. 类属性
    public $attribute1;
    public $attribute2;

    /// 2. 类方法
    function operation1() {
        echo "className operation1<br>";
    }

    function operation2() {
        echo "className operation2<br>";
    }

    function descrip() {
        echo "对象  属性1: $this->attribute1  属性2: $this->attribute2<br>";
    }

    
    /// 3. 构造函数
    function __construct($param1, $param2) {
        echo "参数1: $param1   参数2: $param2<br>";
        $this->attribute1 = $param1;
        $this->attribute2 = $param2;
    }

    /// 4. 析构函数
    function __destruct() {
        echo "这里是析构函数<br>";
    }

}


//// 2、类的实例化
$a = new className("one", "two");
$a->operation1();
$a->descrip();


//// 3、类的继承 重载
class person {
    public $name;
    public $age;

    function __construct($name, $age) {
        echo "--------------------Person 类出初始化方法<br>";
        $this->name = $name;
        $this->age = $age;
    }

    function descri() {
        echo "Person name: $this->name  age:$this->age<br>";
    }
}

class student extends person {

    public $scores;
    public $classId;

    function __construct($name, $age, $scores, $classId) {
        echo "--------------------Student 构造方法<br>";
        parent::__construct($name, $age);
        $this->classId = $classId;
        $this->scores = $scores;
    }

    function descri() {
        parent::descri(); // TODO: Change the autogenerated stub
        echo "Student 方法<br>";
    }
}

echo "========================================================<br>";

$stu = new student("哈哈", 25, 100, 1001);
$stu->descri();



?>